// Time-block planner: a `plannerBlocks` entity covers both the recurring
// weekly skeleton (sleep, meals, hygiene — `recurring: true` + `days`) and
// one-off blocks for a specific date (`recurring: false` + `date`), manual
// or auto-arranged. Auto-arrange is a pure, deterministic bin-packer — no
// AI — that slots the day's Momentum commitments into whatever's left after
// the fixed routine, same "work from data you already entered" philosophy
// as the rest of the app.
import { Moon, UtensilsCrossed, Droplet, BookOpen, Coffee, Dumbbell, Users, CheckCircle2, Circle } from 'lucide-react'
import { dateKey } from './calendarGrid'

export const CATEGORIES = {
  sleep: { label: 'Sleep', tone: 'purple', icon: Moon },
  meal: { label: 'Meal', tone: 'amber', icon: UtensilsCrossed },
  hygiene: { label: 'Routine', tone: 'neutral', icon: Droplet },
  study: { label: 'Study', tone: 'accent', icon: BookOpen },
  break: { label: 'Break', tone: 'green', icon: Coffee },
  exercise: { label: 'Exercise', tone: 'red', icon: Dumbbell },
  social: { label: 'Social', tone: 'purple', icon: Users },
  todo: { label: 'To-do', tone: 'accent', icon: CheckCircle2 },
  custom: { label: 'Other', tone: 'neutral', icon: Circle },
}

export const WEEKDAYS = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat']

export function timeToMinutes(hhmm) {
  if (!hhmm) return null
  const [h, m] = hhmm.split(':').map(Number)
  return h * 60 + m
}

export function minutesToTime(mins) {
  const h = Math.floor(mins / 60) % 24
  const m = mins % 60
  return `${String(h).padStart(2, '0')}:${String(m).padStart(2, '0')}`
}

export function formatTimeLabel(hhmm) {
  if (!hhmm) return ''
  const [h, m] = hhmm.split(':').map(Number)
  const period = h >= 12 ? 'PM' : 'AM'
  const h12 = h % 12 === 0 ? 12 : h % 12
  return m === 0 ? `${h12} ${period}` : `${h12}:${String(m).padStart(2, '0')} ${period}`
}

// Every block that applies to a given date: recurring ones whose `days`
// includes that weekday, plus one-off ones whose `date` matches exactly.
// Sorted by start time; blocks that cross midnight (sleep) sort by start.
export function blocksForDate(blocks, date) {
  const weekday = new Date(date + 'T00:00:00').getDay()
  const key = dateKey(date)
  return blocks
    .filter((b) => (b.recurring ? (b.days || []).includes(weekday) : b.date === key))
    .sort((a, b) => timeToMinutes(a.startTime) - timeToMinutes(b.startTime))
}

// Finds the free gaps in a day given its occupied blocks, within a window
// (defaults to 6am-11pm if no sleep routine exists to infer it from).
export function freeGaps(occupied, windowStart = 6 * 60, windowEnd = 23 * 60) {
  const intervals = occupied
    .map((b) => ({ start: timeToMinutes(b.startTime), end: timeToMinutes(b.endTime) }))
    .filter((b) => b.start !== null && b.end !== null && b.end > b.start)
    .sort((a, b) => a.start - b.start)

  const gaps = []
  let cursor = windowStart
  intervals.forEach((iv) => {
    if (iv.start > cursor) gaps.push({ start: cursor, end: Math.min(iv.start, windowEnd) })
    cursor = Math.max(cursor, iv.end)
  })
  if (cursor < windowEnd) gaps.push({ start: cursor, end: windowEnd })
  return gaps.filter((g) => g.end > g.start)
}

// Slots the date's pending (undone) commitments into whatever's free after
// the recurring routine + any already-placed one-off blocks for that date.
// Returns { placed: [newBlockDrafts], unplaced: [commitmentTitles] } —
// nothing is persisted here, the caller inserts the drafts.
export function autoArrangeDay(data, date) {
  const existing = blocksForDate(data.plannerBlocks, date)
  const sleepBlock = existing.find((b) => b.category === 'sleep')
  const windowStart = sleepBlock ? timeToMinutes(sleepBlock.endTime) : 6 * 60
  const windowEnd = sleepBlock && timeToMinutes(sleepBlock.startTime) > windowStart ? timeToMinutes(sleepBlock.startTime) : 23 * 60

  const gaps = freeGaps(existing, windowStart, windowEnd)
  const todos = data.commitments
    .filter((c) => c.date === date && !c.done)
    .sort((a, b) => (a.deadline || '99:99').localeCompare(b.deadline || '99:99'))

  const placed = []
  const unplaced = []

  todos.forEach((todo) => {
    const duration = Number(todo.estimatedMinutes) || 30
    const gapIndex = gaps.findIndex((g) => g.end - g.start >= duration)
    if (gapIndex === -1) {
      unplaced.push(todo.title)
      return
    }
    const gap = gaps[gapIndex]
    const start = gap.start
    const end = start + duration
    placed.push({
      label: todo.title,
      category: 'todo',
      startTime: minutesToTime(start),
      endTime: minutesToTime(end),
      recurring: false,
      date,
      linkedCommitmentId: todo.id,
      autoGenerated: true,
    })
    if (end < gap.end) gaps[gapIndex] = { start: end, end: gap.end }
    else gaps.splice(gapIndex, 1)
  })

  return { placed, unplaced }
}
