import { uid } from './storage'

function d(offsetDays) {
  const dt = new Date()
  dt.setDate(dt.getDate() + offsetDays)
  return dt.toISOString().slice(0, 10)
}

export function seedDemoData() {
  const habitWorkoutId = uid()
  const habitReadId = uid()
  return {
    version: 1,
    profile: {
      name: 'Jamie Chen',
      gradeLevel: '11th Grade',
      school: 'Lincoln High School',
      bio: 'Aspiring computer scientist interested in AI for healthcare. Founder of a robotics mentorship program.',
      intendedMajor: 'Computer Science',
      gpaScale: 4.0,
      onboarded: true,
    },
    northStar: {
      identity: 'A builder who uses technology to help underserved communities — someone who leads by doing, not just talking.',
      goals: {
        community: 'Grow the tutoring program to 3 schools',
        leadership: 'Hand off Robotics Club to a strong successor',
        impact: 'Get PathwAI to 500 real users',
        skills: 'Ship a full-stack app completely solo',
        curiosity: 'Publish the bioinformatics research',
        character: 'Keep a 30-day streak without missing a day',
      },
      characteristics: ['skills', 'leadership', 'community', 'curiosity', 'analytical'],
      directions: [
        { id: 'engineering-cs', label: 'Engineering & Computer Science' },
        { id: 'sciences', label: 'Natural Sciences & Research' },
        { id: 'education', label: 'Education & Community Work' },
      ],
      traitScores: {
        skills: 95, curiosity: 92, leadership: 90, analytical: 88, community: 85,
        disciplined: 82, impact: 80, independent: 78, character: 75, communicator: 73,
        innovator: 72, collaborator: 70, competitive: 68, strategic: 65, empathetic: 60,
        creative: 58, performer: 40,
      },
    },
    classes: [
      { id: uid(), name: 'AP Calculus BC', subject: 'Math', term: 'Fall 2026', credits: 1, weight: 'ap', grade: 96 },
      { id: uid(), name: 'AP Computer Science A', subject: 'CS', term: 'Fall 2026', credits: 1, weight: 'ap', grade: 98 },
      { id: uid(), name: 'AP US History', subject: 'History', term: 'Fall 2026', credits: 1, weight: 'ap', grade: 91 },
      { id: uid(), name: 'Honors Chemistry', subject: 'Science', term: 'Fall 2026', credits: 1, weight: 'honors', grade: 94 },
      { id: uid(), name: 'English 11', subject: 'English', term: 'Fall 2026', credits: 1, weight: 'regular', grade: 93 },
      { id: uid(), name: 'Spanish IV', subject: 'World Language', term: 'Fall 2026', credits: 1, weight: 'honors', grade: 89 },
    ],
    assignments: [
      { id: uid(), classId: null, title: 'Calc BC Problem Set 12', dueDate: d(0), status: 'todo', priority: 'high' },
      { id: uid(), classId: null, title: 'APUSH DBQ Essay Draft', dueDate: d(0), status: 'todo', priority: 'high' },
      { id: uid(), classId: null, title: 'CS: Binary Search Tree Lab', dueDate: d(2), status: 'todo', priority: 'medium' },
      { id: uid(), classId: null, title: 'Chem Lab Report — Titration', dueDate: d(-1), status: 'todo', priority: 'high' },
      { id: uid(), classId: null, title: 'Spanish Vocabulary Quiz Prep', dueDate: d(4), status: 'todo', priority: 'low' },
      { id: uid(), classId: null, title: 'English Essay: The Great Gatsby', dueDate: d(6), status: 'done', priority: 'medium' },
    ],
    exams: [
      { id: uid(), name: 'AP Calculus BC', date: d(24), examType: 'ap' },
      { id: uid(), name: 'AP Computer Science A', date: d(18), examType: 'ap' },
      { id: uid(), name: 'AP US History', date: d(31), examType: 'ap' },
      { id: uid(), name: 'IB Mathematics: Analysis and Approaches', date: d(45), examType: 'ib' },
      { id: uid(), name: 'A-Level Physics', date: d(52), examType: 'a-level' },
    ],
    studyTasks: [],
    projects: [
      {
        id: uid(),
        title: 'PathwAI — AI College Advisor',
        type: 'project',
        description: 'A web app that uses ML to recommend colleges based on student profile and interests. Built with React and a Python backend.',
        role: 'Founder & Lead Developer',
        date: d(-120),
        link: 'https://github.com',
        tags: ['React', 'Python', 'Machine Learning'],
        featured: true,
        dimensions: ['skills', 'impact'],
        problem: 'Students pick colleges based on rankings and vibes, not fit — a mismatch that shows up later as transfers and dropouts.',
        action: 'Built an ML recommender that scores fit against a student\'s actual profile, interests, and goals, not just prestige.',
        impactWho: '500+ students have used it to shortlist schools; several counselors now recommend it directly.',
        growth: 'Learned that the hard part of "AI for X" is almost never the model — it\'s getting the data model of X right.',
      },
      {
        id: uid(),
        title: 'Regional Science Fair — 1st Place, Computer Science',
        type: 'competition',
        description: 'Awarded first place for a research project on using computer vision to detect early signs of plant disease.',
        role: 'Independent Researcher',
        date: d(-200),
        link: '',
        tags: ['Computer Vision', 'Research'],
        featured: true,
        dimensions: ['curiosity', 'impact'],
      },
      {
        id: uid(),
        title: 'Summer Research Internship — State University Bioinformatics Lab',
        type: 'research',
        description: 'Worked with a graduate research team analyzing genomic datasets for cancer biomarker discovery.',
        role: 'Research Intern',
        date: d(-60),
        link: '',
        tags: ['Bioinformatics', 'Data Analysis'],
        featured: false,
        dimensions: ['curiosity', 'skills'],
      },
      {
        id: uid(),
        title: 'jamiechen.dev — Personal Website',
        type: 'website',
        description: 'Personal site showcasing projects, writing, and a blog about learning to code.',
        role: 'Designer & Developer',
        date: d(-30),
        link: 'https://example.com',
        tags: ['Web Design'],
        featured: false,
        dimensions: ['skills'],
      },
    ],
    activities: [
      {
        id: uid(),
        title: 'Robotics Club — Team Captain',
        category: 'activity',
        org: 'Lincoln High School',
        hoursPerWeek: 8,
        weeksPerYear: 30,
        startDate: d(-400),
        endDate: '',
        description: 'Lead a 15-person team building competition robots; mentor underclassmen in CAD and programming.',
        dimensions: ['leadership', 'skills'],
      },
      {
        id: uid(),
        title: 'Tutoring for Underserved Students',
        category: 'volunteering',
        org: 'City Learning Center',
        scope: 'state-regional',
        hoursPerWeek: 3,
        weeksPerYear: 40,
        startDate: d(-300),
        endDate: '',
        description: 'Weekly math and science tutoring for middle school students from low-income families.',
        dimensions: ['community'],
        problem: 'Middle schoolers from low-income families were falling behind in math with no affordable tutoring options nearby.',
        action: 'Organized and taught weekly small-group math and science sessions at the local learning center.',
        impactWho: '12 students tutored over two semesters; three moved up a full grade level in math.',
        growth: 'Learned that patience and meeting someone where they are matters more than how well you know the material.',
      },
      {
        id: uid(),
        title: 'Software Engineering Intern',
        category: 'internship',
        org: 'Local Health-Tech Startup',
        hoursPerWeek: 15,
        weeksPerYear: 10,
        startDate: d(-70),
        endDate: d(-10),
        description: 'Built internal dashboard tools using React and worked with the data team on patient scheduling features.',
        dimensions: ['skills', 'leadership'],
      },
    ],
    opportunities: [
      {
        id: uid(),
        title: 'MIT — Early Action',
        schoolName: 'MIT',
        date: d(120),
        category: 'college-application',
        applicationRound: 'early-action',
        status: 'not-started',
        notes: '',
        checklist: [
          { id: uid(), text: 'Draft Common App essay', done: true },
          { id: uid(), text: 'Request two teacher recommendations', done: false },
          { id: uid(), text: 'Send official transcript', done: false },
        ],
      },
      {
        id: uid(),
        title: 'Stanford — Restrictive EA',
        schoolName: 'Stanford',
        date: d(120),
        category: 'college-application',
        applicationRound: 'early-action',
        status: 'not-started',
        notes: '',
        checklist: [],
      },
      {
        id: uid(),
        title: 'State University — Regular Decision',
        schoolName: 'State University',
        date: d(180),
        category: 'college-application',
        applicationRound: 'regular',
        status: 'not-started',
        notes: '',
        checklist: [],
      },
      {
        id: uid(),
        title: 'National Merit Scholarship',
        schoolName: '',
        date: d(45),
        category: 'scholarship',
        applicationRound: '',
        status: 'in-progress',
        notes: 'Need to finalize essay',
        checklist: [{ id: uid(), text: 'Finalize scholarship essay', done: false }],
      },
      {
        id: uid(),
        title: 'Regeneron Science Talent Search',
        schoolName: '',
        date: d(75),
        category: 'competition',
        applicationRound: '',
        status: 'not-started',
        notes: '',
        checklist: [
          { id: uid(), text: 'Write research report', done: false },
          { id: uid(), text: 'Get mentor endorsement', done: false },
        ],
      },
      {
        id: uid(),
        title: 'MIT PRIMES Research Program',
        schoolName: '',
        date: d(60),
        category: 'research-program',
        applicationRound: '',
        status: 'not-started',
        notes: '',
        checklist: [],
      },
      {
        id: uid(),
        title: 'Summer Science Program',
        schoolName: '',
        date: d(90),
        category: 'summer-program',
        applicationRound: '',
        status: 'not-started',
        notes: '',
        checklist: [],
      },
    ],
    goals: [],
    tasks: [
      { id: uid(), title: 'Email robotics mentor about regionals', dueDate: d(0), done: false },
      { id: uid(), title: 'Draft Common App essay outline', dueDate: d(1), done: false },
    ],
    habits: [
      { id: habitWorkoutId, title: 'Morning workout', archived: false },
      { id: habitReadId, title: 'Read 20 minutes', archived: false },
    ],
    habitLogs: [
      ...[0, -1, -2, -3, -4].map((offset) => ({ id: uid(), habitId: habitWorkoutId, date: d(offset) })),
      ...[-1, -2, -4, -6].map((offset) => ({ id: uid(), habitId: habitReadId, date: d(offset) })),
    ],
    momentumSessions: [
      { id: uid(), commitmentId: null, taskLabel: 'Calc BC problem set', plannedMinutes: 25, actualMinutes: 25, goalCompleted: true, focusRating: 4, date: d(0) },
      { id: uid(), commitmentId: null, taskLabel: 'Read Chapter 4 — APUSH', plannedMinutes: 45, actualMinutes: 40, goalCompleted: true, focusRating: 5, date: d(-1) },
      { id: uid(), commitmentId: null, taskLabel: 'CS lab debugging', plannedMinutes: 25, actualMinutes: 25, goalCompleted: false, focusRating: 3, date: d(-3) },
    ],
    distractions: [
      { id: uid(), description: '', minutesLost: 0, time: '', date: d(0), stayedFocused: true, note: '' },
      { id: uid(), description: '', minutesLost: 0, time: '', date: d(-1), stayedFocused: true, note: '' },
      { id: uid(), description: '', minutesLost: 0, time: '', date: d(-2), stayedFocused: false, note: 'Phone notifications' },
      { id: uid(), description: '', minutesLost: 0, time: '', date: d(-4), stayedFocused: true, note: '' },
    ],
    reflections: [
      { id: uid(), date: d(-1), accomplished: 'Finished the Calc BC problem set and started the APUSH essay draft.', blocked: 'Spent too long context-switching between subjects.', improve: 'Block out one subject at a time tomorrow.' },
      { id: uid(), date: d(-2), accomplished: 'Robotics practice went well — the new arm design finally works.', blocked: 'Nothing major today.', improve: 'Keep this pace up.' },
    ],
    streak: { datesActive: [0, -1, -2, -3, -4].map((offset) => d(offset)) },
    awards: [
      {
        id: uid(),
        title: 'Regional Science Fair — 1st Place, Computer Science',
        level: 'state-regional',
        category: 'STEM',
        issuer: 'State Science Foundation',
        date: d(-200),
        description: 'Awarded for a computer vision project detecting early signs of plant disease.',
      },
      {
        id: uid(),
        title: 'Principal\'s Honor Roll',
        level: 'school',
        category: 'Academic',
        issuer: 'Lincoln High School',
        date: d(-90),
        description: '',
      },
    ],
    recommenders: [
      {
        id: uid(),
        name: 'Ms. Rodriguez',
        subject: 'AP Computer Science A teacher',
        status: 'confirmed',
        deadline: d(30),
        notes: 'Mentored PathwAI from a rough prototype to something 500+ students actually use — saw the debugging grind firsthand.',
      },
      {
        id: uid(),
        name: 'Coach Patel',
        subject: 'Robotics Club advisor',
        status: 'asked',
        deadline: d(45),
        notes: '',
      },
    ],
    testEntries: [
      {
        id: uid(),
        testType: 'sat',
        date: d(-200),
        registrationDeadline: '',
        status: 'completed',
        scores: { readingWriting: 750, math: 700 },
        notes: 'Strong on reading, ran out of time on the last math section.',
      },
      {
        id: uid(),
        testType: 'sat',
        date: d(-90),
        registrationDeadline: '',
        status: 'completed',
        scores: { readingWriting: 700, math: 780 },
        notes: 'Much better pacing on math this time, reading dipped a bit.',
      },
      {
        id: uid(),
        testType: 'sat',
        date: d(40),
        registrationDeadline: d(10),
        status: 'planned',
        scores: {},
        notes: '',
      },
    ],
    testPrep: { targets: { sat: { readingWriting: 770, math: 780 } } },
  }
}
