// A curated, editorial reference — not a live ranking feed. This app is
// client-only with no backend, so this list is static, hand-picked for name
// recognition and regional spread (not an exhaustive top-50). Grounded in
// QS World University Rankings 2026 and THE World University Rankings 2026
// for standing, but `values` is an editorial characterization of each
// school's culture, not a scraped official tagline — treat it as a
// starting point for research, not a verdict. `size`/`setting`/`type` are
// broad editorial tiers, not precise enrollment figures — verify exact
// numbers on the school's own site before relying on them. `majors` tags
// map to the ids in lib/majorFit.js and drive the Major Fit quiz's
// "Recommended For You" matching — they're a curated "strong here," not an
// exhaustive list of every program the school offers.
export const REGIONS = ['US', 'UK', 'Canada', 'Europe', 'Asia', 'Australia']

export const UNIVERSITIES = [
  {
    id: 'mit',
    name: 'Massachusetts Institute of Technology',
    city: 'Cambridge',
    country: 'United States',
    region: 'US',
    size: 'Small',
    setting: 'Urban',
    type: 'Private',
    notableFor: ['Engineering', 'Computer Science', 'Physics'],
    majors: ['cs', 'elec-eng', 'mech-eng', 'physics', 'math', 'biomed-eng'],
    values: "Hands-on and problem-solving culture — \"mens et manus\" (mind and hand). Rigorous, collaborative, and famously unpretentious about credentials.",
    website: 'https://www.mit.edu',
  },
  {
    id: 'stanford',
    name: 'Stanford University',
    city: 'Stanford',
    country: 'United States',
    region: 'US',
    size: 'Medium',
    setting: 'Suburban',
    type: 'Private',
    notableFor: ['Computer Science', 'Engineering', 'Entrepreneurship'],
    majors: ['cs', 'business', 'elec-eng', 'biology', 'data-science'],
    values: 'Interdisciplinary and entrepreneurial — students are pushed to combine fields and turn ideas into ventures, not just study them.',
    website: 'https://www.stanford.edu',
  },
  {
    id: 'harvard',
    name: 'Harvard University',
    city: 'Cambridge',
    country: 'United States',
    region: 'US',
    size: 'Medium',
    setting: 'Urban',
    type: 'Private',
    notableFor: ['Liberal Arts', 'Law', 'Economics', 'Medicine'],
    majors: ['economics', 'poli-sci', 'english', 'history', 'business'],
    values: 'Breadth over specialization — a liberal-arts core meant to produce generalists who can lead across fields, not just experts in one.',
    website: 'https://www.harvard.edu',
  },
  {
    id: 'princeton',
    name: 'Princeton University',
    city: 'Princeton',
    country: 'United States',
    region: 'US',
    size: 'Small',
    setting: 'Suburban',
    type: 'Private',
    notableFor: ['Mathematics', 'Physics', 'Public Policy'],
    majors: ['math', 'physics', 'poli-sci', 'economics'],
    values: '"In the nation\'s service and the service of humanity" — small, undergraduate-focused, with a strong senior-thesis research tradition.',
    website: 'https://www.princeton.edu',
  },
  {
    id: 'yale',
    name: 'Yale University',
    city: 'New Haven',
    country: 'United States',
    region: 'US',
    size: 'Medium',
    setting: 'Urban',
    type: 'Private',
    notableFor: ['Law', 'Humanities', 'Drama'],
    majors: ['english', 'history', 'poli-sci', 'philosophy'],
    values: 'Residential-college system built around close mentorship and the arts — strong identity around debate, writing, and performance.',
    website: 'https://www.yale.edu',
  },
  {
    id: 'caltech',
    name: 'California Institute of Technology',
    city: 'Pasadena',
    country: 'United States',
    region: 'US',
    size: 'Small',
    setting: 'Suburban',
    type: 'Private',
    notableFor: ['Physics', 'Aerospace Engineering', 'Chemistry'],
    majors: ['physics', 'math', 'mech-eng', 'biology'],
    values: 'Tiny, intensely research-driven, and unapologetically technical — depth over breadth, science first.',
    website: 'https://www.caltech.edu',
  },
  {
    id: 'cmu',
    name: 'Carnegie Mellon University',
    city: 'Pittsburgh',
    country: 'United States',
    region: 'US',
    size: 'Medium',
    setting: 'Urban',
    type: 'Private',
    notableFor: ['Computer Science', 'Robotics', 'Drama & Fine Arts'],
    majors: ['cs', 'elec-eng', 'art-design', 'data-science'],
    values: '"My heart is in the work" — a builder culture that pairs elite CS/robotics with a surprisingly strong arts conservatory.',
    website: 'https://www.cmu.edu',
  },
  {
    id: 'berkeley',
    name: 'UC Berkeley',
    city: 'Berkeley',
    country: 'United States',
    region: 'US',
    size: 'Large',
    setting: 'Urban',
    type: 'Public',
    notableFor: ['Computer Science', 'Public Policy', 'Environmental Science'],
    majors: ['cs', 'environmental-science', 'poli-sci', 'economics', 'business'],
    values: 'Public-mission scale with an activist streak — big, research-intensive, and proud of its role in public higher education.',
    website: 'https://www.berkeley.edu',
  },
  {
    id: 'upenn',
    name: 'University of Pennsylvania',
    city: 'Philadelphia',
    country: 'United States',
    region: 'US',
    size: 'Medium',
    setting: 'Urban',
    type: 'Private',
    notableFor: ['Business (Wharton)', 'Nursing', 'Communication'],
    majors: ['business', 'biology', 'poli-sci', 'cs'],
    values: 'Practical and professional-minded for an Ivy — Ben Franklin\'s "useful knowledge" ethos still shows in how career-focused it is.',
    website: 'https://www.upenn.edu',
  },
  {
    id: 'columbia',
    name: 'Columbia University',
    city: 'New York City',
    country: 'United States',
    region: 'US',
    size: 'Medium',
    setting: 'Urban',
    type: 'Private',
    notableFor: ['Journalism', 'Political Science', 'Literature'],
    majors: ['poli-sci', 'english', 'business', 'biology'],
    values: 'The Core Curriculum — every student reads the same foundational texts, whatever their major — anchors a famously intense, city-immersed culture.',
    website: 'https://www.columbia.edu',
  },
  {
    id: 'cornell',
    name: 'Cornell University',
    city: 'Ithaca',
    country: 'United States',
    region: 'US',
    size: 'Large',
    setting: 'Small City',
    type: 'Private',
    notableFor: ['Engineering', 'Agriculture & Life Sciences', 'Hotel Administration'],
    majors: ['mech-eng', 'biology', 'business', 'cs', 'environmental-science'],
    values: '"Any person, any study" — a land-grant mission built into an Ivy, meaning genuinely enormous breadth across colleges.',
    website: 'https://www.cornell.edu',
  },
  {
    id: 'jhu',
    name: 'Johns Hopkins University',
    city: 'Baltimore',
    country: 'United States',
    region: 'US',
    size: 'Medium',
    setting: 'Urban',
    type: 'Private',
    notableFor: ['Medicine', 'Biomedical Engineering', 'International Studies'],
    majors: ['biomed-eng', 'biology', 'poli-sci'],
    values: "America's first research university, and it still shows — research output and lab access for undergrads are unusually serious, early.",
    website: 'https://www.jhu.edu',
  },
  {
    id: 'duke',
    name: 'Duke University',
    city: 'Durham',
    country: 'United States',
    region: 'US',
    size: 'Medium',
    setting: 'Suburban',
    type: 'Private',
    notableFor: ['Public Policy', 'Biomedical Engineering', 'Economics'],
    majors: ['biology', 'economics', 'business', 'biomed-eng'],
    values: 'High-energy and basketball-mad, but underneath that: a rigorous pre-med/pre-law pipeline and genuine research access from year one.',
    website: 'https://www.duke.edu',
  },
  {
    id: 'northwestern',
    name: 'Northwestern University',
    city: 'Evanston',
    country: 'United States',
    region: 'US',
    size: 'Medium',
    setting: 'Suburban',
    type: 'Private',
    notableFor: ['Journalism (Medill)', 'Theatre', 'Engineering'],
    majors: ['communications', 'business', 'cs', 'art-design'],
    values: 'An unusual combination — elite journalism and theatre programs sitting right next to a strong engineering school, same campus, same energy.',
    website: 'https://www.northwestern.edu',
  },
  {
    id: 'michigan',
    name: 'University of Michigan',
    city: 'Ann Arbor',
    country: 'United States',
    region: 'US',
    size: 'Large',
    setting: 'Suburban',
    type: 'Public',
    notableFor: ['Business (Ross)', 'Engineering', 'Political Science'],
    majors: ['cs', 'business', 'biology', 'poli-sci'],
    values: 'A public flagship at Ivy-caliber depth across nearly every field — huge, spirited, and genuinely strong almost everywhere you look.',
    website: 'https://www.umich.edu',
  },
  {
    id: 'ucla',
    name: 'UCLA',
    city: 'Los Angeles',
    country: 'United States',
    region: 'US',
    size: 'Large',
    setting: 'Urban',
    type: 'Public',
    notableFor: ['Film & Theater', 'Biology', 'Psychology'],
    majors: ['biology', 'art-design', 'business', 'psychology'],
    values: 'Hollywood\'s backyard feeds a real film/TV pipeline, but it\'s also a serious public research university with strong sciences.',
    website: 'https://www.ucla.edu',
  },
  {
    id: 'uchicago',
    name: 'University of Chicago',
    city: 'Chicago',
    country: 'United States',
    region: 'US',
    size: 'Medium',
    setting: 'Urban',
    type: 'Private',
    notableFor: ['Economics', 'Philosophy', 'Mathematics'],
    majors: ['economics', 'philosophy', 'math', 'poli-sci'],
    values: '"The life of the mind" — famously the most academically intense Core Curriculum in the US; birthplace of Chicago-school economics.',
    website: 'https://www.uchicago.edu',
  },
  {
    id: 'georgia-tech',
    name: 'Georgia Institute of Technology',
    city: 'Atlanta',
    country: 'United States',
    region: 'US',
    size: 'Large',
    setting: 'Urban',
    type: 'Public',
    notableFor: ['Engineering', 'Computer Science', 'Aerospace'],
    majors: ['mech-eng', 'elec-eng', 'cs'],
    values: 'A pure engineering powerhouse with deep co-op and industry ties — "progress and service" is the actual campus motto.',
    website: 'https://www.gatech.edu',
  },
  {
    id: 'ut-austin',
    name: 'University of Texas at Austin',
    city: 'Austin',
    country: 'United States',
    region: 'US',
    size: 'Large',
    setting: 'Urban',
    type: 'Public',
    notableFor: ['Business (McCombs)', 'Computer Science', 'Communications'],
    majors: ['business', 'cs', 'elec-eng', 'communications'],
    values: 'Enormous and entrepreneurial, plugged directly into Austin\'s tech and energy industries — "what starts here changes the world."',
    website: 'https://www.utexas.edu',
  },
  {
    id: 'nyu',
    name: 'New York University',
    city: 'New York City',
    country: 'United States',
    region: 'US',
    size: 'Large',
    setting: 'Urban',
    type: 'Private',
    notableFor: ['Business (Stern)', 'Film (Tisch)', 'Economics'],
    majors: ['business', 'art-design', 'cs', 'economics'],
    values: 'No real campus — the city is the campus. A genuine global network of satellite sites (Abu Dhabi, Shanghai) if you want to study abroad seriously.',
    website: 'https://www.nyu.edu',
  },
  {
    id: 'rice',
    name: 'Rice University',
    city: 'Houston',
    country: 'United States',
    region: 'US',
    size: 'Small',
    setting: 'Suburban',
    type: 'Private',
    notableFor: ['Engineering', 'Architecture', 'Space Science'],
    majors: ['elec-eng', 'biomed-eng', 'math', 'art-design'],
    values: 'Tiny and tight-knit with a residential-college system, plus real NASA/Houston medical-center research access most small schools can\'t offer.',
    website: 'https://www.rice.edu',
  },
  {
    id: 'williams',
    name: 'Williams College',
    city: 'Williamstown',
    country: 'United States',
    region: 'US',
    size: 'Small',
    setting: 'Rural',
    type: 'Private',
    notableFor: ['Liberal Arts', 'Economics', 'Art History'],
    majors: ['english', 'history', 'economics', 'art-design'],
    values: 'A top liberal arts college built around the "tutorial" — two students and a professor, one-on-one argument every week.',
    website: 'https://www.williams.edu',
  },
  {
    id: 'oxford',
    name: 'University of Oxford',
    city: 'Oxford',
    country: 'United Kingdom',
    region: 'UK',
    size: 'Medium',
    setting: 'Small City',
    type: 'Public',
    notableFor: ['PPE (Politics, Philosophy & Economics)', 'Humanities', 'Medicine'],
    majors: ['poli-sci', 'philosophy', 'history', 'biology'],
    values: 'The tutorial system — small, argument-driven weekly sessions with a tutor — built to make students defend their thinking, not just absorb it.',
    website: 'https://www.ox.ac.uk',
  },
  {
    id: 'cambridge',
    name: 'University of Cambridge',
    city: 'Cambridge',
    country: 'United Kingdom',
    region: 'UK',
    size: 'Medium',
    setting: 'Small City',
    type: 'Public',
    notableFor: ['Mathematics', 'Natural Sciences', 'Engineering'],
    majors: ['math', 'physics', 'mech-eng', 'biology'],
    values: 'Deep, collegiate, and research-first — the college system means intense small-group supervision layered on top of a rigorous degree.',
    website: 'https://www.cam.ac.uk',
  },
  {
    id: 'imperial',
    name: 'Imperial College London',
    city: 'London',
    country: 'United Kingdom',
    region: 'UK',
    size: 'Medium',
    setting: 'Urban',
    type: 'Public',
    notableFor: ['Engineering', 'Medicine', 'Computer Science'],
    majors: ['mech-eng', 'elec-eng', 'biomed-eng', 'physics'],
    values: 'STEM-only focus — no humanities faculty by design, which makes for an intensely technical, research-driven culture.',
    website: 'https://www.imperial.ac.uk',
  },
  {
    id: 'lse',
    name: 'London School of Economics',
    city: 'London',
    country: 'United Kingdom',
    region: 'UK',
    size: 'Small',
    setting: 'Urban',
    type: 'Public',
    notableFor: ['Economics', 'Political Science', 'Law'],
    majors: ['economics', 'poli-sci', 'business'],
    values: '"To understand the causes of things" — small, social-science-only, and unusually plugged into real-world policy and finance.',
    website: 'https://www.lse.ac.uk',
  },
  {
    id: 'ucl',
    name: 'University College London',
    city: 'London',
    country: 'United Kingdom',
    region: 'UK',
    size: 'Large',
    setting: 'Urban',
    type: 'Public',
    notableFor: ['Medicine', 'Architecture', 'Neuroscience'],
    majors: ['biomed-eng', 'art-design', 'poli-sci', 'biology'],
    values: "Founded to be secular and open when Oxford and Cambridge weren't — still carries that founding streak of academic inclusiveness.",
    website: 'https://www.ucl.ac.uk',
  },
  {
    id: 'edinburgh',
    name: 'University of Edinburgh',
    city: 'Edinburgh',
    country: 'United Kingdom',
    region: 'UK',
    size: 'Large',
    setting: 'Urban',
    type: 'Public',
    notableFor: ['Informatics', 'Medicine', 'Literature'],
    majors: ['biology', 'poli-sci', 'english', 'physics'],
    values: "A Scottish Enlightenment pedigree — genuinely strong across sciences and arts alike, in one of Europe's most livable capitals.",
    website: 'https://www.ed.ac.uk',
  },
  {
    id: 'kcl',
    name: "King's College London",
    city: 'London',
    country: 'United Kingdom',
    region: 'UK',
    size: 'Large',
    setting: 'Urban',
    type: 'Public',
    notableFor: ['War Studies', 'Medicine', 'Law'],
    majors: ['poli-sci', 'biology', 'business'],
    values: 'The only War Studies department of its kind, right in Westminster\'s backyard — policy and international relations feel unusually close to the real thing here.',
    website: 'https://www.kcl.ac.uk',
  },
  {
    id: 'manchester',
    name: 'University of Manchester',
    city: 'Manchester',
    country: 'United Kingdom',
    region: 'UK',
    size: 'Large',
    setting: 'Urban',
    type: 'Public',
    notableFor: ['Physics', 'Materials Science', 'Business'],
    majors: ['physics', 'biology', 'business'],
    values: "Where the atom was first split and graphene was discovered — an industrial city's grit paired with genuine scientific firsts.",
    website: 'https://www.manchester.ac.uk',
  },
  {
    id: 'toronto',
    name: 'University of Toronto',
    city: 'Toronto',
    country: 'Canada',
    region: 'Canada',
    size: 'Large',
    setting: 'Urban',
    type: 'Public',
    notableFor: ['Computer Science', 'Medicine', 'Engineering'],
    majors: ['cs', 'biology', 'business', 'data-science'],
    values: "Canada's largest research university — big, diverse, and the birthplace of major AI research (deep learning pioneers taught here).",
    website: 'https://www.utoronto.ca',
  },
  {
    id: 'mcgill',
    name: 'McGill University',
    city: 'Montreal',
    country: 'Canada',
    region: 'Canada',
    size: 'Large',
    setting: 'Urban',
    type: 'Public',
    notableFor: ['Medicine', 'Life Sciences', 'Law'],
    majors: ['biology', 'business', 'poli-sci'],
    values: 'Often called "the Harvard of Canada" — international student body, strong research output, bilingual city life.',
    website: 'https://www.mcgill.ca',
  },
  {
    id: 'ubc',
    name: 'University of British Columbia',
    city: 'Vancouver',
    country: 'Canada',
    region: 'Canada',
    size: 'Large',
    setting: 'Urban',
    type: 'Public',
    notableFor: ['Forestry & Environmental Science', 'Computer Science', 'Business'],
    majors: ['environmental-science', 'cs', 'business'],
    values: 'Research-intensive with a strong sustainability and outdoors identity — academics alongside a famously livable campus.',
    website: 'https://www.ubc.ca',
  },
  {
    id: 'waterloo',
    name: 'University of Waterloo',
    city: 'Waterloo',
    country: 'Canada',
    region: 'Canada',
    size: 'Large',
    setting: 'Suburban',
    type: 'Public',
    notableFor: ['Computer Science', 'Engineering', 'Co-op Programs'],
    majors: ['cs', 'elec-eng', 'mech-eng'],
    values: "The co-op program is the whole identity — students alternate school terms with paid industry work, and it feeds Silicon Valley heavily.",
    website: 'https://www.uwaterloo.ca',
  },
  {
    id: 'queens',
    name: "Queen's University",
    city: 'Kingston',
    country: 'Canada',
    region: 'Canada',
    size: 'Medium',
    setting: 'Small City',
    type: 'Public',
    notableFor: ['Commerce', 'Engineering', 'Life Sciences'],
    majors: ['business', 'biology', 'poli-sci'],
    values: 'Famous school spirit and a tight-knit, small-city campus feel that\'s rare among Canadian research universities this strong.',
    website: 'https://www.queensu.ca',
  },
  {
    id: 'eth-zurich',
    name: 'ETH Zurich',
    city: 'Zurich',
    country: 'Switzerland',
    region: 'Europe',
    size: 'Medium',
    setting: 'Urban',
    type: 'Public',
    notableFor: ['Engineering', 'Computer Science', 'Physics'],
    majors: ['mech-eng', 'cs', 'physics', 'math'],
    values: "Continental Europe's top technical university — no-frills, rigorous, Einstein's alma mater; substance over prestige theater.",
    website: 'https://ethz.ch',
  },
  {
    id: 'epfl',
    name: 'EPFL (École Polytechnique Fédérale de Lausanne)',
    city: 'Lausanne',
    country: 'Switzerland',
    region: 'Europe',
    size: 'Small',
    setting: 'Small City',
    type: 'Public',
    notableFor: ['Engineering', 'Computer Science', 'Life Sciences'],
    majors: ['cs', 'mech-eng', 'biomed-eng'],
    values: 'Young and fast-growing relative to its peers — heavily international faculty, strong startup and robotics culture.',
    website: 'https://www.epfl.ch',
  },
  {
    id: 'tum',
    name: 'Technical University of Munich',
    city: 'Munich',
    country: 'Germany',
    region: 'Europe',
    size: 'Large',
    setting: 'Urban',
    type: 'Public',
    notableFor: ['Mechanical Engineering', 'Computer Science', 'Physics'],
    majors: ['mech-eng', 'elec-eng', 'physics'],
    values: 'Industry-linked engineering culture — deep ties to Germany\'s automotive and manufacturing base, entrepreneurial in recent years.',
    website: 'https://www.tum.de',
  },
  {
    id: 'sorbonne',
    name: 'Sorbonne University',
    city: 'Paris',
    country: 'France',
    region: 'Europe',
    size: 'Large',
    setting: 'Urban',
    type: 'Public',
    notableFor: ['Humanities', 'Physics', 'Medicine'],
    majors: ['physics', 'history', 'english', 'philosophy'],
    values: 'Centuries-old intellectual tradition (the historic Sorbonne name) now paired with a modern, research-focused merger of sciences and letters.',
    website: 'https://www.sorbonne-universite.fr',
  },
  {
    id: 'tu-delft',
    name: 'TU Delft',
    city: 'Delft',
    country: 'Netherlands',
    region: 'Europe',
    size: 'Large',
    setting: 'Small City',
    type: 'Public',
    notableFor: ['Aerospace Engineering', 'Civil Engineering', 'Architecture'],
    majors: ['mech-eng', 'elec-eng', 'environmental-science'],
    values: "The Netherlands' top technical university — practical, water-management and infrastructure expertise runs deep for obvious geographic reasons.",
    website: 'https://www.tudelft.nl',
  },
  {
    id: 'amsterdam',
    name: 'University of Amsterdam',
    city: 'Amsterdam',
    country: 'Netherlands',
    region: 'Europe',
    size: 'Large',
    setting: 'Urban',
    type: 'Public',
    notableFor: ['Economics', 'Psychology', 'Political Science'],
    majors: ['economics', 'poli-sci', 'psychology'],
    values: 'Strong social sciences in one of the most internationally-minded, English-friendly cities to study in continental Europe.',
    website: 'https://www.uva.nl',
  },
  {
    id: 'trinity-dublin',
    name: 'Trinity College Dublin',
    city: 'Dublin',
    country: 'Ireland',
    region: 'Europe',
    size: 'Medium',
    setting: 'Urban',
    type: 'Public',
    notableFor: ['Literature', 'History', 'Life Sciences'],
    majors: ['english', 'history', 'biology', 'business'],
    values: "Ireland's oldest university — a historic, literary campus (alumni include Wilde and Beckett) right in the middle of Dublin.",
    website: 'https://www.tcd.ie',
  },
  {
    id: 'u-tokyo',
    name: 'University of Tokyo',
    city: 'Tokyo',
    country: 'Japan',
    region: 'Asia',
    size: 'Large',
    setting: 'Urban',
    type: 'Public',
    notableFor: ['Engineering', 'Natural Sciences', 'Law'],
    majors: ['mech-eng', 'physics', 'poli-sci', 'biology'],
    values: "Japan's most prestigious university — highly selective entrance exams, strong government and research-institute pipelines.",
    website: 'https://www.u-tokyo.ac.jp',
  },
  {
    id: 'tsinghua',
    name: 'Tsinghua University',
    city: 'Beijing',
    country: 'China',
    region: 'Asia',
    size: 'Large',
    setting: 'Urban',
    type: 'Public',
    notableFor: ['Engineering', 'Computer Science', 'Architecture'],
    majors: ['cs', 'mech-eng', 'elec-eng', 'business'],
    values: "Known as China's MIT — intensely competitive admissions, strong government and tech-industry pipeline (many national leaders are alumni).",
    website: 'https://www.tsinghua.edu.cn',
  },
  {
    id: 'peking',
    name: 'Peking University',
    city: 'Beijing',
    country: 'China',
    region: 'Asia',
    size: 'Large',
    setting: 'Urban',
    type: 'Public',
    notableFor: ['Humanities', 'Economics', 'Political Science'],
    majors: ['poli-sci', 'economics', 'history', 'philosophy'],
    values: "China's oldest modern university and its humanities counterpart to Tsinghua — historically the center of Chinese intellectual and political life.",
    website: 'https://www.pku.edu.cn',
  },
  {
    id: 'nus',
    name: 'National University of Singapore',
    city: 'Singapore',
    country: 'Singapore',
    region: 'Asia',
    size: 'Large',
    setting: 'Urban',
    type: 'Public',
    notableFor: ['Computer Science', 'Business', 'Public Policy'],
    majors: ['cs', 'business', 'poli-sci'],
    values: "Southeast Asia's top-ranked university — global outlook by design, with extensive overseas exchange and dual-degree programs.",
    website: 'https://www.nus.edu.sg',
  },
  {
    id: 'hku',
    name: 'University of Hong Kong',
    city: 'Hong Kong',
    country: 'Hong Kong',
    region: 'Asia',
    size: 'Medium',
    setting: 'Urban',
    type: 'Public',
    notableFor: ['Business', 'Medicine', 'Law'],
    majors: ['business', 'biology', 'poli-sci', 'economics'],
    values: "Hong Kong's oldest university, deeply tied to the city's role as a global finance hub — genuinely international student body.",
    website: 'https://www.hku.hk',
  },
  {
    id: 'hkust',
    name: 'Hong Kong University of Science and Technology',
    city: 'Hong Kong',
    country: 'Hong Kong',
    region: 'Asia',
    size: 'Medium',
    setting: 'Suburban',
    type: 'Public',
    notableFor: ['Business', 'Engineering', 'Computer Science'],
    majors: ['cs', 'business', 'elec-eng'],
    values: "Young (founded 1991) but elite fast — an unusually strong business-and-engineering combination for a school this new.",
    website: 'https://www.hkust.edu.hk',
  },
  {
    id: 'iit-bombay',
    name: 'IIT Bombay',
    city: 'Mumbai',
    country: 'India',
    region: 'Asia',
    size: 'Medium',
    setting: 'Urban',
    type: 'Public',
    notableFor: ['Engineering', 'Computer Science', 'Technology'],
    majors: ['cs', 'mech-eng', 'elec-eng'],
    values: "India's most selective engineering school — the entrance exam (JEE) is legendarily hard, and the alumni network runs deep in global tech.",
    website: 'https://www.iitb.ac.in',
  },
  {
    id: 'kaist',
    name: 'KAIST',
    city: 'Daejeon',
    country: 'South Korea',
    region: 'Asia',
    size: 'Small',
    setting: 'Small City',
    type: 'Public',
    notableFor: ['Computer Science', 'Engineering', 'Robotics'],
    majors: ['cs', 'mech-eng', 'elec-eng'],
    values: "Korea's top technical/research university — English-taught, research-first, and government-founded specifically to build technical talent.",
    website: 'https://www.kaist.ac.kr',
  },
  {
    id: 'snu',
    name: 'Seoul National University',
    city: 'Seoul',
    country: 'South Korea',
    region: 'Asia',
    size: 'Large',
    setting: 'Urban',
    type: 'Public',
    notableFor: ['Business', 'Engineering', 'Political Science'],
    majors: ['business', 'biology', 'poli-sci', 'cs'],
    values: "Korea's most prestigious and comprehensive university — broad strength across nearly every field, not just one specialty.",
    website: 'https://www.snu.ac.kr',
  },
  {
    id: 'melbourne',
    name: 'University of Melbourne',
    city: 'Melbourne',
    country: 'Australia',
    region: 'Australia',
    size: 'Large',
    setting: 'Urban',
    type: 'Public',
    notableFor: ['Medicine', 'Law', 'Arts & Humanities'],
    majors: ['biology', 'poli-sci', 'art-design', 'history'],
    values: "Australia's top-ranked university — broad undergraduate degrees followed by professional graduate schools, modeled partly on the US system.",
    website: 'https://www.unimelb.edu.au',
  },
  {
    id: 'anu',
    name: 'Australian National University',
    city: 'Canberra',
    country: 'Australia',
    region: 'Australia',
    size: 'Medium',
    setting: 'Small City',
    type: 'Public',
    notableFor: ['Political Science', 'International Relations', 'Physics'],
    majors: ['poli-sci', 'physics', 'environmental-science'],
    values: "Founded by the government as a research-first institution — smaller and more research-dense than Australia's other leading schools.",
    website: 'https://www.anu.edu.au',
  },
  {
    id: 'sydney',
    name: 'University of Sydney',
    city: 'Sydney',
    country: 'Australia',
    region: 'Australia',
    size: 'Large',
    setting: 'Urban',
    type: 'Public',
    notableFor: ['Medicine', 'Engineering', 'Business'],
    majors: ['biology', 'mech-eng', 'business'],
    values: "Australia's oldest university — large, comprehensive, with deep alumni networks across law, medicine, and government.",
    website: 'https://www.sydney.edu.au',
  },
  {
    id: 'monash',
    name: 'Monash University',
    city: 'Melbourne',
    country: 'Australia',
    region: 'Australia',
    size: 'Large',
    setting: 'Suburban',
    type: 'Public',
    notableFor: ['Pharmacy', 'Business', 'Biomedical Engineering'],
    majors: ['biomed-eng', 'business', 'biology'],
    values: "Australia's largest university — young relative to its peers but has climbed fast, especially in pharmacy and medical research.",
    website: 'https://www.monash.edu',
  },
]

export const SIZES = ['Small', 'Medium', 'Large']
export const SETTINGS = ['Urban', 'Suburban', 'Small City', 'Rural']
export const TYPES = ['Public', 'Private']

// Ranks universities by how many of the given major ids they're tagged
// strong in (see each entry's `majors` field) — used to turn a Major Fit
// quiz result into "Recommended For You" schools. Ties broken by region
// spread so results aren't all from one country.
export function recommendUniversities(majorIds, count = 6) {
  if (!majorIds || majorIds.length === 0) return []
  const scored = UNIVERSITIES.map((u) => ({
    university: u,
    score: u.majors.filter((m) => majorIds.includes(m)).length,
  })).filter((s) => s.score > 0)

  scored.sort((a, b) => b.score - a.score)

  const seenRegions = new Set()
  const prioritized = []
  const rest = []
  scored.forEach((s) => {
    if (!seenRegions.has(s.university.region)) {
      seenRegions.add(s.university.region)
      prioritized.push(s)
    } else {
      rest.push(s)
    }
  })

  return [...prioritized, ...rest].slice(0, count).map((s) => s.university)
}
