// A curated, editorial reference — not a live ranking feed. This app is
// client-only with no backend, so this list is static, hand-picked for name
// recognition and regional spread (not an exhaustive top-50). Grounded in
// QS World University Rankings 2026 and THE World University Rankings 2026
// for standing, but `values` is an editorial characterization of each
// school's culture, not a scraped official tagline — treat it as a
// starting point for research, not a verdict.
export const REGIONS = ['US', 'UK', 'Canada', 'Europe', 'Asia', 'Australia']

export const UNIVERSITIES = [
  {
    id: 'mit',
    name: 'Massachusetts Institute of Technology',
    city: 'Cambridge',
    country: 'United States',
    region: 'US',
    notableFor: ['Engineering', 'Computer Science', 'Physics'],
    values: "Hands-on and problem-solving culture — \"mens et manus\" (mind and hand). Rigorous, collaborative, and famously unpretentious about credentials.",
    website: 'https://www.mit.edu',
  },
  {
    id: 'stanford',
    name: 'Stanford University',
    city: 'Stanford',
    country: 'United States',
    region: 'US',
    notableFor: ['Computer Science', 'Engineering', 'Entrepreneurship'],
    values: 'Interdisciplinary and entrepreneurial — students are pushed to combine fields and turn ideas into ventures, not just study them.',
    website: 'https://www.stanford.edu',
  },
  {
    id: 'harvard',
    name: 'Harvard University',
    city: 'Cambridge',
    country: 'United States',
    region: 'US',
    notableFor: ['Liberal Arts', 'Law', 'Economics', 'Medicine'],
    values: 'Breadth over specialization — a liberal-arts core meant to produce generalists who can lead across fields, not just experts in one.',
    website: 'https://www.harvard.edu',
  },
  {
    id: 'princeton',
    name: 'Princeton University',
    city: 'Princeton',
    country: 'United States',
    region: 'US',
    notableFor: ['Mathematics', 'Physics', 'Public Policy'],
    values: '"In the nation\'s service and the service of humanity" — small, undergraduate-focused, with a strong senior-thesis research tradition.',
    website: 'https://www.princeton.edu',
  },
  {
    id: 'yale',
    name: 'Yale University',
    city: 'New Haven',
    country: 'United States',
    region: 'US',
    notableFor: ['Law', 'Humanities', 'Drama'],
    values: 'Residential-college system built around close mentorship and the arts — strong identity around debate, writing, and performance.',
    website: 'https://www.yale.edu',
  },
  {
    id: 'caltech',
    name: 'California Institute of Technology',
    city: 'Pasadena',
    country: 'United States',
    region: 'US',
    notableFor: ['Physics', 'Aerospace Engineering', 'Chemistry'],
    values: 'Tiny, intensely research-driven, and unapologetically technical — depth over breadth, science first.',
    website: 'https://www.caltech.edu',
  },
  {
    id: 'cmu',
    name: 'Carnegie Mellon University',
    city: 'Pittsburgh',
    country: 'United States',
    region: 'US',
    notableFor: ['Computer Science', 'Robotics', 'Drama & Fine Arts'],
    values: '"My heart is in the work" — a builder culture that pairs elite CS/robotics with a surprisingly strong arts conservatory.',
    website: 'https://www.cmu.edu',
  },
  {
    id: 'berkeley',
    name: 'UC Berkeley',
    city: 'Berkeley',
    country: 'United States',
    region: 'US',
    notableFor: ['Computer Science', 'Public Policy', 'Environmental Science'],
    values: 'Public-mission scale with an activist streak — big, research-intensive, and proud of its role in public higher education.',
    website: 'https://www.berkeley.edu',
  },
  {
    id: 'oxford',
    name: 'University of Oxford',
    city: 'Oxford',
    country: 'United Kingdom',
    region: 'UK',
    notableFor: ['PPE (Politics, Philosophy & Economics)', 'Humanities', 'Medicine'],
    values: 'The tutorial system — small, argument-driven weekly sessions with a tutor — built to make students defend their thinking, not just absorb it.',
    website: 'https://www.ox.ac.uk',
  },
  {
    id: 'cambridge',
    name: 'University of Cambridge',
    city: 'Cambridge',
    country: 'United Kingdom',
    region: 'UK',
    notableFor: ['Mathematics', 'Natural Sciences', 'Engineering'],
    values: 'Deep, collegiate, and research-first — the college system means intense small-group supervision layered on top of a rigorous degree.',
    website: 'https://www.cam.ac.uk',
  },
  {
    id: 'imperial',
    name: 'Imperial College London',
    city: 'London',
    country: 'United Kingdom',
    region: 'UK',
    notableFor: ['Engineering', 'Medicine', 'Computer Science'],
    values: 'STEM-only focus — no humanities faculty by design, which makes for an intensely technical, research-driven culture.',
    website: 'https://www.imperial.ac.uk',
  },
  {
    id: 'lse',
    name: 'London School of Economics',
    city: 'London',
    country: 'United Kingdom',
    region: 'UK',
    notableFor: ['Economics', 'Political Science', 'Law'],
    values: '"To understand the causes of things" — small, social-science-only, and unusually plugged into real-world policy and finance.',
    website: 'https://www.lse.ac.uk',
  },
  {
    id: 'ucl',
    name: 'University College London',
    city: 'London',
    country: 'United Kingdom',
    region: 'UK',
    notableFor: ['Medicine', 'Architecture', 'Neuroscience'],
    values: "Founded to be secular and open when Oxford and Cambridge weren't — still carries that founding streak of academic inclusiveness.",
    website: 'https://www.ucl.ac.uk',
  },
  {
    id: 'toronto',
    name: 'University of Toronto',
    city: 'Toronto',
    country: 'Canada',
    region: 'Canada',
    notableFor: ['Computer Science', 'Medicine', 'Engineering'],
    values: "Canada's largest research university — big, diverse, and the birthplace of major AI research (deep learning pioneers taught here).",
    website: 'https://www.utoronto.ca',
  },
  {
    id: 'mcgill',
    name: 'McGill University',
    city: 'Montreal',
    country: 'Canada',
    region: 'Canada',
    notableFor: ['Medicine', 'Life Sciences', 'Law'],
    values: 'Often called "the Harvard of Canada" — international student body, strong research output, bilingual city life.',
    website: 'https://www.mcgill.ca',
  },
  {
    id: 'ubc',
    name: 'University of British Columbia',
    city: 'Vancouver',
    country: 'Canada',
    region: 'Canada',
    notableFor: ['Forestry & Environmental Science', 'Computer Science', 'Business'],
    values: 'Research-intensive with a strong sustainability and outdoors identity — academics alongside a famously livable campus.',
    website: 'https://www.ubc.ca',
  },
  {
    id: 'eth-zurich',
    name: 'ETH Zurich',
    city: 'Zurich',
    country: 'Switzerland',
    region: 'Europe',
    notableFor: ['Engineering', 'Computer Science', 'Physics'],
    values: "Continental Europe's top technical university — no-frills, rigorous, Einstein's alma mater; substance over prestige theater.",
    website: 'https://ethz.ch',
  },
  {
    id: 'epfl',
    name: 'EPFL (École Polytechnique Fédérale de Lausanne)',
    city: 'Lausanne',
    country: 'Switzerland',
    region: 'Europe',
    notableFor: ['Engineering', 'Computer Science', 'Life Sciences'],
    values: 'Young and fast-growing relative to its peers — heavily international faculty, strong startup and robotics culture.',
    website: 'https://www.epfl.ch',
  },
  {
    id: 'tum',
    name: 'Technical University of Munich',
    city: 'Munich',
    country: 'Germany',
    region: 'Europe',
    notableFor: ['Mechanical Engineering', 'Computer Science', 'Physics'],
    values: 'Industry-linked engineering culture — deep ties to Germany\'s automotive and manufacturing base, entrepreneurial in recent years.',
    website: 'https://www.tum.de',
  },
  {
    id: 'sorbonne',
    name: 'Sorbonne University',
    city: 'Paris',
    country: 'France',
    region: 'Europe',
    notableFor: ['Humanities', 'Physics', 'Medicine'],
    values: 'Centuries-old intellectual tradition (the historic Sorbonne name) now paired with a modern, research-focused merger of sciences and letters.',
    website: 'https://www.sorbonne-universite.fr',
  },
  {
    id: 'u-tokyo',
    name: 'University of Tokyo',
    city: 'Tokyo',
    country: 'Japan',
    region: 'Asia',
    notableFor: ['Engineering', 'Natural Sciences', 'Law'],
    values: "Japan's most prestigious university — highly selective entrance exams, strong government and research-institute pipelines.",
    website: 'https://www.u-tokyo.ac.jp',
  },
  {
    id: 'tsinghua',
    name: 'Tsinghua University',
    city: 'Beijing',
    country: 'China',
    region: 'Asia',
    notableFor: ['Engineering', 'Computer Science', 'Architecture'],
    values: "Known as China's MIT — intensely competitive admissions, strong government and tech-industry pipeline (many national leaders are alumni).",
    website: 'https://www.tsinghua.edu.cn',
  },
  {
    id: 'nus',
    name: 'National University of Singapore',
    city: 'Singapore',
    country: 'Singapore',
    region: 'Asia',
    notableFor: ['Computer Science', 'Business', 'Public Policy'],
    values: "Southeast Asia's top-ranked university — global outlook by design, with extensive overseas exchange and dual-degree programs.",
    website: 'https://www.nus.edu.sg',
  },
  {
    id: 'melbourne',
    name: 'University of Melbourne',
    city: 'Melbourne',
    country: 'Australia',
    region: 'Australia',
    notableFor: ['Medicine', 'Law', 'Arts & Humanities'],
    values: "Australia's top-ranked university — broad undergraduate degrees followed by professional graduate schools, modeled partly on the US system.",
    website: 'https://www.unimelb.edu.au',
  },
  {
    id: 'anu',
    name: 'Australian National University',
    city: 'Canberra',
    country: 'Australia',
    region: 'Australia',
    notableFor: ['Political Science', 'International Relations', 'Physics'],
    values: "Founded by the government as a research-first institution — smaller and more research-dense than Australia's other leading schools.",
    website: 'https://www.anu.edu.au',
  },
  {
    id: 'sydney',
    name: 'University of Sydney',
    city: 'Sydney',
    country: 'Australia',
    region: 'Australia',
    notableFor: ['Medicine', 'Engineering', 'Business'],
    values: "Australia's oldest university — large, comprehensive, with deep alumni networks across law, medicine, and government.",
    website: 'https://www.sydney.edu.au',
  },
]
