import { useMemo, useState } from 'react'
import { ChevronLeft, ChevronRight, Plus, Pencil, Trash2, Sparkles, CalendarClock } from 'lucide-react'
import { useStore } from '../../context/StoreContext'
import { useToast } from '../../context/ToastContext'
import { Card } from '../ui/Card'
import { Button, IconButton } from '../ui/Button'
import { Field, Input, Select } from '../ui/Form'
import { Modal } from '../ui/Modal'
import { Badge, EmptyState } from '../ui/Misc'
import { dateKey } from '../../lib/calendarGrid'
import { formatDate } from '../../lib/dates'
import { CATEGORIES, WEEKDAYS, blocksForDate, timeToMinutes, formatTimeLabel, autoArrangeDay } from '../../lib/planner'

const WINDOW_START = 5 * 60
const WINDOW_END = 24 * 60
const WINDOW_MIN = WINDOW_END - WINDOW_START
const HOUR_PX = 36
const GRID_HEIGHT = (WINDOW_MIN / 60) * HOUR_PX

const emptyBlock = { label: '', category: 'study', startTime: '', endTime: '', date: '', recurring: false, days: [] }

function startOfWeek(d) {
  const x = new Date(d)
  x.setDate(x.getDate() - x.getDay())
  x.setHours(0, 0, 0, 0)
  return x
}

function blockStyle(block) {
  let start = timeToMinutes(block.startTime)
  let end = timeToMinutes(block.endTime)
  if (end <= start) end = WINDOW_END // overnight block — clip to end of visible window
  start = Math.max(start, WINDOW_START)
  end = Math.min(end, WINDOW_END)
  if (end <= start) return null
  return {
    top: `${((start - WINDOW_START) / WINDOW_MIN) * 100}%`,
    height: `${Math.max(((end - start) / WINDOW_MIN) * 100, 2.2)}%`,
  }
}

export function WeekView() {
  const { data, addItem, updateItem, removeItem } = useStore()
  const { push } = useToast()
  const today = new Date()
  const [weekStart, setWeekStart] = useState(startOfWeek(today))
  const [selected, setSelected] = useState(today)
  const [modalOpen, setModalOpen] = useState(false)
  const [editingId, setEditingId] = useState(null)
  const [form, setForm] = useState(emptyBlock)

  const weekDays = useMemo(() => Array.from({ length: 7 }, (_, i) => {
    const d = new Date(weekStart)
    d.setDate(d.getDate() + i)
    return d
  }), [weekStart])

  const selectedKey = dateKey(selected)
  const selectedBlocks = useMemo(() => blocksForDate(data.plannerBlocks, selectedKey), [data.plannerBlocks, selectedKey])
  const selectedCommitments = useMemo(() => data.commitments.filter((c) => c.date === selectedKey), [data.commitments, selectedKey])

  function openAdd() {
    setForm({ ...emptyBlock, date: selectedKey })
    setEditingId(null)
    setModalOpen(true)
  }
  function openEdit(b) {
    setForm({ ...emptyBlock, ...b })
    setEditingId(b.id)
    setModalOpen(true)
  }
  function save(e) {
    e.preventDefault()
    if (!form.label.trim() || !form.startTime || !form.endTime) return
    const payload = { ...form, recurring: false, days: [] }
    if (editingId) updateItem('plannerBlocks', editingId, payload)
    else addItem('plannerBlocks', payload)
    setModalOpen(false)
  }

  function handleAutoArrange() {
    const stale = data.plannerBlocks.filter((b) => !b.recurring && b.date === selectedKey && b.autoGenerated)
    const cleaned = { ...data, plannerBlocks: data.plannerBlocks.filter((b) => !stale.includes(b)) }
    const { placed, unplaced } = autoArrangeDay(cleaned, selectedKey)
    stale.forEach((b) => removeItem('plannerBlocks', b.id))
    placed.forEach((draft) => addItem('plannerBlocks', draft))
    if (placed.length === 0 && unplaced.length === 0) {
      push('Nothing to arrange', { description: "Add today's to-dos in Today's Mission first, then come back." })
    } else if (unplaced.length > 0) {
      push(`${unplaced.length} item${unplaced.length === 1 ? "" : 's'} didn't fit`, { description: unplaced.join(', ') })
    } else {
      push(`Arranged ${placed.length} task${placed.length === 1 ? '' : 's'} into today`, { tone: 'success' })
    }
  }

  return (
    <div className="space-y-4">
      <Card className="p-4 sm:p-5">
        <div className="flex items-center justify-between mb-4">
          <p className="text-[16px] font-semibold text-neutral-900 dark:text-white">
            {formatDate(weekDays[0], { year: undefined })} – {formatDate(weekDays[6])}
          </p>
          <div className="flex items-center gap-1.5">
            <Button variant="secondary" size="sm" onClick={() => { setWeekStart(startOfWeek(today)); setSelected(today) }}>Today</Button>
            <div className="flex items-center gap-0.5">
              <button onClick={() => setWeekStart((w) => { const n = new Date(w); n.setDate(n.getDate() - 7); return n })} className="w-8 h-8 rounded-full flex items-center justify-center text-neutral-500 hover:bg-black/[0.05] dark:hover:bg-white/10">
                <ChevronLeft size={17} />
              </button>
              <button onClick={() => setWeekStart((w) => { const n = new Date(w); n.setDate(n.getDate() + 7); return n })} className="w-8 h-8 rounded-full flex items-center justify-center text-neutral-500 hover:bg-black/[0.05] dark:hover:bg-white/10">
                <ChevronRight size={17} />
              </button>
            </div>
          </div>
        </div>

        <div className="grid grid-cols-[36px_repeat(7,1fr)] gap-1 sm:gap-1.5">
          <div />
          {weekDays.map((d) => {
            const isToday = dateKey(d) === dateKey(today)
            const isSelected = dateKey(d) === selectedKey
            return (
              <button
                key={dateKey(d)}
                onClick={() => setSelected(d)}
                className={`text-center py-1.5 rounded-lg transition-colors ${isSelected ? 'bg-accent-500/10' : 'hover:bg-black/[0.03] dark:hover:bg-white/5'}`}
              >
                <p className="text-[10.5px] font-medium text-neutral-400">{WEEKDAYS[d.getDay()]}</p>
                <p className={`text-[13px] font-semibold mt-0.5 w-6 h-6 mx-auto flex items-center justify-center rounded-full ${isToday ? 'bg-accent-500 text-white' : 'text-neutral-700 dark:text-neutral-200'}`}>
                  {d.getDate()}
                </p>
              </button>
            )
          })}

          <div className="relative" style={{ height: GRID_HEIGHT }}>
            {Array.from({ length: WINDOW_MIN / 60 + 1 }, (_, i) => (
              <div key={i} className="absolute left-0 right-0 text-right pr-1 text-[9.5px] text-neutral-300 dark:text-neutral-600" style={{ top: `${(i * HOUR_PX) - 5}px` }}>
                {formatTimeLabel(`${String((WINDOW_START / 60 + i) % 24).padStart(2, '0')}:00`).replace(':00', '').replace(' ', '')}
              </div>
            ))}
          </div>
          {weekDays.map((d) => {
            const key = dateKey(d)
            const blocks = blocksForDate(data.plannerBlocks, key)
            const isSelected = key === selectedKey
            return (
              <div
                key={key}
                onClick={() => setSelected(d)}
                className={`relative rounded-lg border cursor-pointer ${isSelected ? 'border-accent-500/40 bg-accent-500/5' : 'border-black/5 dark:border-white/10'}`}
                style={{ height: GRID_HEIGHT }}
              >
                {Array.from({ length: WINDOW_MIN / 60 }, (_, i) => (
                  <div key={i} className="absolute left-0 right-0 border-t border-black/[0.03] dark:border-white/[0.04]" style={{ top: `${i * HOUR_PX}px` }} />
                ))}
                {blocks.map((b) => {
                  const style = blockStyle(b)
                  if (!style) return null
                  const C = CATEGORIES[b.category] || CATEGORIES.custom
                  const toneBg = {
                    neutral: 'bg-neutral-400', accent: 'bg-accent-500', green: 'bg-green-500', amber: 'bg-amber-500', red: 'bg-red-500', purple: 'bg-purple-500',
                  }[C.tone]
                  return (
                    <div
                      key={b.id}
                      title={`${b.label} · ${formatTimeLabel(b.startTime)}–${formatTimeLabel(b.endTime)}`}
                      className={`absolute left-0.5 right-0.5 rounded ${toneBg} opacity-80 overflow-hidden px-0 sm:px-1`}
                      style={style}
                    >
                      <span className="hidden sm:inline text-[8.5px] font-medium text-white leading-tight whitespace-nowrap">{b.label}</span>
                    </div>
                  )
                })}
              </div>
            )
          })}
        </div>
      </Card>

      <Card className="p-5">
        <div className="flex items-center justify-between gap-3 flex-wrap mb-4">
          <p className="text-[14px] font-semibold text-neutral-900 dark:text-white">{formatDate(selected, { weekday: 'long' })}</p>
          <div className="flex items-center gap-2">
            <Button size="sm" variant="secondary" icon={Sparkles} onClick={handleAutoArrange} disabled={selectedCommitments.length === 0}>
              Auto-Arrange
            </Button>
            <Button size="sm" icon={Plus} onClick={openAdd}>Add Block</Button>
          </div>
        </div>

        {selectedBlocks.length === 0 ? (
          <EmptyState icon={CalendarClock} title="Nothing scheduled" description="Add a routine, a study block, or auto-arrange today's to-dos." />
        ) : (
          <div className="divide-y divide-black/5 dark:divide-white/10">
            {selectedBlocks.map((b) => {
              const C = CATEGORIES[b.category] || CATEGORIES.custom
              return (
                <div key={b.id} className="flex items-center gap-3 py-2.5 group">
                  <div className="w-8 h-8 rounded-lg bg-black/[0.04] dark:bg-white/10 flex items-center justify-center flex-shrink-0">
                    <C.icon size={14} className="text-neutral-500" />
                  </div>
                  <div className="min-w-0 flex-1">
                    <div className="flex items-center gap-2 flex-wrap">
                      <p className="text-[13.5px] font-medium text-neutral-900 dark:text-white">{b.label}</p>
                      <Badge tone={C.tone}>{C.label}</Badge>
                      {b.recurring && <Badge tone="neutral">Routine</Badge>}
                    </div>
                    <p className="text-[12px] text-neutral-400 mt-0.5">{formatTimeLabel(b.startTime)} – {formatTimeLabel(b.endTime)}</p>
                  </div>
                  {!b.recurring && (
                    <div className="flex items-center gap-0.5 opacity-0 group-hover:opacity-100 transition-opacity flex-shrink-0">
                      <IconButton icon={Pencil} onClick={() => openEdit(b)} />
                      <IconButton icon={Trash2} onClick={() => removeItem('plannerBlocks', b.id)} />
                    </div>
                  )}
                </div>
              )
            })}
          </div>
        )}
      </Card>

      <Modal
        open={modalOpen}
        onClose={() => setModalOpen(false)}
        title={editingId ? 'Edit Block' : 'Add Block'}
        footer={
          <>
            <Button variant="ghost" onClick={() => setModalOpen(false)}>Cancel</Button>
            <Button onClick={save}>{editingId ? 'Save Changes' : 'Add Block'}</Button>
          </>
        }
      >
        <form onSubmit={save} className="space-y-4">
          <Field label="Label">
            <Input autoFocus value={form.label} onChange={(e) => setForm((prev) => ({ ...prev, label: e.target.value }))} placeholder="e.g. Study for Chem test" />
          </Field>
          <div className="grid grid-cols-2 gap-3">
            <Field label="Category">
              <Select value={form.category} onChange={(e) => setForm((prev) => ({ ...prev, category: e.target.value }))}>
                {Object.entries(CATEGORIES).map(([k, v]) => (
                  <option key={k} value={k}>{v.label}</option>
                ))}
              </Select>
            </Field>
            <Field label="Date">
              <Input type="date" value={form.date} onChange={(e) => setForm((prev) => ({ ...prev, date: e.target.value }))} />
            </Field>
          </div>
          <div className="grid grid-cols-2 gap-3">
            <Field label="Start time">
              <Input type="time" value={form.startTime} onChange={(e) => setForm((prev) => ({ ...prev, startTime: e.target.value }))} />
            </Field>
            <Field label="End time">
              <Input type="time" value={form.endTime} onChange={(e) => setForm((prev) => ({ ...prev, endTime: e.target.value }))} />
            </Field>
          </div>
        </form>
      </Modal>
    </div>
  )
}
